name: "HLK2450 mmWave Sensor Configurator"
description: "Advanced ESPHome add-on for HLK2450 mmWave sensor configuration with real-time visualization and polygon zone creation"
version: "1.0.2"
# Trigger workflow build
slug: "hlk2450-configurator"
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: "Web interface"
webui: "http://[HOST]:[PORT:5000]"
ingress: true
ingress_port: 5000
panel_icon: mdi:radar
panel_title: "HLK2450 Configurator"
hassio_api: true
hassio_role: default
homeassistant_api: true
host_network: false
options:
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  ssl: bool
  certfile: str
  keyfile: str
image: "ghcr.io/nmcrae85/hlk2450-configurator-{arch}"
