name: Build and Publish Add-on

on:
  push:
    branches:
      - main
    paths:
      - 'hlk2450-configurator/**'
  pull_request:
    paths:
      - 'hlk2450-configurator/**'
  release:
    types:
      - published

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: wifispray/hlk2450-configurator

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        arch: [amd64, arm64, armv7]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.arch }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=1.0.0

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./hlk2450-configurator
          platforms: linux/${{ matrix.arch == 'armv7' && 'arm/v7' || matrix.arch }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max